FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

# Install Node.js
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash - \
    && apt-get install -y \
        nodejs \
    && rm -rf /var/lib/apt/lists/*

COPY ["Source/schema.web/schema.web.csproj", "src/Source/schema.web/"]
WORKDIR "/src/Source/schema.web"
RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet restore "schema.web.csproj"
COPY "Source/schema.web/" "/src/Source/schema.web/"

RUN --mount=type=cache,id=nuget,target=/root/.nuget/packages \
    dotnet build -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "schema.web.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "schema.web.dll"]
